[package]
name = "Nova"
version = "0.1.0"
edition = "2024"
autobins = false
autoexamples = false
autotests = false
autobenches = false

[[bin]]
name = "Nova"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
icu = { version = "2.1.1", features = ["compiled_data"] }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
uuid = { version = "1", features = ["v4", "v5", "serde"] }
toml = "0.8"
rmp-serde = "1"
typeid = "1.0.3"
