[workspace]
resolver = "3"
members = [
    "nova-incremental",
    "nova-analyze",
    "nova-compile"
]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
icu = { version = "2.1.1", features = ["compiled_data"] }
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
uuid = { version = "1", features = ["v4", "v5", "serde"] }
toml = "1.0.3+spec-1.1.0"
rmp-serde = "1"
typeid = "1.0.3"
dashmap = "6"
futures = "0.3"
parking_lot = "0.12"
