[package]
name = "nova-analyze"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
icu = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
rmp-serde = { workspace = true }
nova-incremental-neo = { path = "../nova-incremental-neo" }

